### ISSUE TITLE
Filter breaks if a class has a property without set accessor

### ISSUE THREAD

**Issue by hairlesshobo** [Danielku15/OpenApiQuery#5]
When attempting to use oData filtering on a class that has a readonly property (eg: `public string { get; }`), it throws an exception in the expression binding of `ExpandClause.cs`.

```
System.ArgumentException: The property 'System.String Schema' has no 'set' accessor (Parameter 'member')
   at System.Linq.Expressions.Expression.ValidateSettableFieldOrPropertyMember(MemberInfo member, Type& memberType)
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at OpenApiQuery.ExpandClause.BuildMemberInit(Type itemType, Expression source, IDictionary`2 expands) in C:\Users\crosssa\Projects\Upgrade-O-Matic\OpenApiQuery\OpenApiQuery\ExpandClause.cs:line 124
   at OpenApiQuery.ExpandClause.BuildSelectLambdaExpression(Type itemType, IDictionary`2 expands) in C:\Users\crosssa\Projects\Upgrade-O-Matic\OpenApiQuery\OpenApiQuery\ExpandClause.cs:line 90
   at OpenApiQuery.ExpandQueryOption.ApplyTo[T](IQueryable`1 queryable) in C:\Users\crosssa\Projects\Upgrade-O-Matic\OpenApiQuery\OpenApiQuery\ExpandQueryOption.cs:line 29
   at OpenApiQuery.OpenApiQueryOptions.ApplyTo[T](IQueryable`1 queryable, CancellationToken cancellationToken) in C:\Users\crosssa\Projects\Upgrade-O-Matic\OpenApiQuery\OpenApiQuery\OpenApiQueryOptions.cs:line 108
   at OpenApiQuery.OpenApiQueryResultOutputFormatter.WriteResponseBodyAsync[T](OutputFormatterWriteContext context, Encoding selectedEncoding) in C:\Users\crosssa\Projects\Upgrade-O-Matic\OpenApiQuery\OpenApiQuery\OpenApiQueryResultOutputFormatter.cs:line 122
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

In this case, I haven't even provided an `$expand` filter.

I am currently researching the issue, but figured I would go ahead and create the issue so if I manage to find a solution, I can submit a PR.

**Comment by hairlesshobo** [comment]
OK so that was a pretty simple fix.. all I had to do was skip doing anything in `BuildMemberInit()` if the property has `CanWrite` set to false. Will submit a PR real quick for it.

**Comment by Danielku15** [comment]
The property selection in the current implementation is still experimental. The final goal will be to use the definition from an OpenAPI specification with corresponding mapping to CLR types (comparable to the IEdmModel in OData) I think it does not make sense to tackle such side topics now until not even the base implementation/architecture is done.
